title: 'willclark.tech'
description: 'return tech || philosophy || nonsense'

theme: 'jekyll-theme-cayman'
paginate: 10

google_analytics: 'UA-69040906-1'
disqus_short_name: 'willclarktech'

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
